services:
  verandb:
    build: https://github.com/LonelyqueenoftheNorth/openApiListItemManagement
    image: verandb
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - verandb_data:/app
